add main content
catharkriss/hw.BEM pull request #1
Opened 2024-06-22 14:36 UTC by catharkriss

2024-06-24 08:39 UTC, a1exalexander requested changes
<img width="1226" alt="image" src="https://github.com/catharkriss/hw.BEM/assets/40409129/db10a16b-d027-442a-a721-634b71381189">
<img width="1222" alt="image" src="https://github.com/catharkriss/hw.BEM/assets/40409129/fde697d6-d61d-45e8-ab7e-5dd7545ddd82">

- [ ] (1) – карточки не в контейнері
- [ ] (2) – полоска не на місці, якщо екран невеликий
- [ ] (3) – hover ефект відсутній, як в фігмі
- [ ] (4) – відсутній відступ внизу сайта, через це на вузьких екранах елементи прижаті до низу 

Ось, як в фігмі!
<img width="825" alt="image" src="https://github.com/catharkriss/hw.BEM/assets/40409129/76c00816-3c15-4272-9814-d743585b441b">

2024-06-24 08:39 UTC, a1exalexander commented on index.html
> +                <h4 class="team-list__heading">John Handson</h4>
на сайті є h1 і h4 але нема h2 та h3
пропускати рівень заголовків не можна!

2024-06-24 08:39 UTC, a1exalexander commented on index.html
> +            </div>
це список!

2024-06-24 08:39 UTC, a1exalexander commented on index.html
> +            <div class="team-list card__section-item">
це список!

2024-06-29 07:46 UTC, catharkriss commented on index.html
> +            <div class="team-list card__section-item">
додала всі зміни, які ти зазначив. але в мене питання: мій overlay на картках має синій фон, який при зменшенні екрана виходить за рамки самої фотографії, на яку накладається цей overlay. підкажи, будь ласка, як це можна виправити? у футера не має такої проблеми і там все добре накладається

2024-07-04 14:07 UTC, a1exalexander approved these changes
Молодець!

2024-07-04 14:08 UTC, a1exalexander commented on index.html
> +            <div class="team-list card__section-item">
треба щоб той фон був всередині самого тега за картинкою або поряд з нею

2024-07-04 14:09 UTC, a1exalexander commented on index.html
> +            <div class="team-list card__section-item">
![image](https://github.com/catharkriss/hw.BEM/assets/40409129/15ee865d-c621-479a-a10b-efd4cc78ef23)

2024-07-05 14:45 UTC, merged